### ISSUE TITLE
command: mist list error: thread 'main' panicked at src/style.rs:71:53:

### ISSUE THREAD

**Issue by almusx** [makedeb/mpr-cli#54]
thread 'main' panicked at src/style.rs:71:53:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.6.4-x64v3-xanmod1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
Manufacturer: BIOSTAR Group
Product Name: B550MX/E PRO

**Comment by ArgentumCation** [comment]
Here's what I'm getting, might be related
```sh
$ RUST_BACKTRACE=full mist search --mpr-only lazygit

thread 'main' panicked at src/style.rs:64:53:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x59ae3300002c - <unknown>
   1:     0x59ae3302e7c0 - <unknown>
   2:     0x59ae32ffcd2f - <unknown>
   3:     0x59ae32fffe14 - <unknown>
   4:     0x59ae33001617 - <unknown>
   5:     0x59ae3300137f - <unknown>
   6:     0x59ae33001a98 - <unknown>
   7:     0x59ae33001949 - <unknown>
   8:     0x59ae330004f6 - <unknown>
   9:     0x59ae330016e2 - <unknown>
  10:     0x59ae32beeaa5 - <unknown>
  11:     0x59ae32beeb63 - <unknown>
  12:     0x59ae32c3d8b7 - <unknown>
  13:     0x59ae32c3dfde - <unknown>
  14:     0x59ae32c2319f - <unknown>
  15:     0x59ae32c2ecaf - <unknown>
  16:     0x59ae32c197fa - <unknown>
  17:     0x59ae32c23623 - <unknown>
  18:     0x59ae32c384a9 - <unknown>
  19:     0x59ae32ff46b7 - <unknown>
  20:     0x59ae32c3849e - <unknown>
  21:     0x7f4229428150 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  22:     0x7f4229428209 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  23:     0x59ae32bef635 - <unknown>
  24:                0x0 - <unknown>
```

**Comment by Dantescur** [comment]
same error here, different command

```
❯ RUST_BACKTRACE=full mist list
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/style.rs:71:53
stack backtrace:
   0:     0x6378f7969f11 - <unknown>
   1:     0x6378f7998def - <unknown>
   2:     0x6378f7965d57 - <unknown>
   3:     0x6378f7969d25 - <unknown>
   4:     0x6378f796b403 - <unknown>
   5:     0x6378f796b194 - <unknown>
   6:     0x6378f796b989 - <unknown>
   7:     0x6378f796b841 - <unknown>
   8:     0x6378f796a376 - <unknown>
   9:     0x6378f796b5d2 - <unknown>
  10:     0x6378f75252a3 - <unknown>
  11:     0x6378f7525333 - <unknown>
  12:     0x6378f7535f74 - <unknown>
  13:     0x6378f75366a8 - <unknown>
  14:     0x6378f752b07e - <unknown>
  15:     0x6378f754212f - <unknown>
  16:     0x6378f75310fa - <unknown>
  17:     0x6378f7536d93 - <unknown>
  18:     0x6378f7536da9 - <unknown>
  19:     0x6378f795d67b - <unknown>
  20:     0x6378f7531195 - <unknown>
  21:     0x7fb87b42a1ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  22:     0x7fb87b42a28b - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  23:     0x6378f7525d75 - <unknown>
  24:                0x0 - <unknown>
```
